version: "3.9"

services:
  influx:
    image: influxdb:latest
    volumes:
      - influxData:/var/lib/influxdb2
      - $PWD/config/influx.yml:/etc/influxdb2/config.yml
    ports:
      - 8086:8086
    environment:
      DOCKER_INFLUXDB_INIT_MODE: ${DOCKER_INFLUXDB_INIT_MODE}
      DOCKER_INFLUXDB_INIT_USERNAME: ${DOCKER_INFLUXDB_INIT_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${DOCKER_INFLUXDB_INIT_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${DOCKER_INFLUXDB_INIT_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${DOCKER_INFLUXDB_INIT_BUCKET}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
    networks:
      drip-db:

  cargo-drip:
    image: cargo-drip:latest
    build:
      context: cargo-drip
    ports:
      - 8080:8080
    environment:
      DRIP_INFLUXDB_URL: http://influx:8086
      DRIP_INFLUXDB_TOKEN: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
      DRIP_INFLUXDB_BUCKET: ${DOCKER_INFLUXDB_INIT_BUCKET}
    networks:
      drip-db:

volumes:
  influxData:

networks:
  drip-db:
